import { PixelArt } from '../../shared/pixel-sprite/pixel-sprite';

/** The Team page's two pixel-art surprises (see AboutTeam). Each is a few frames of a character
 *  grid: one letter per cell, `.` transparent, palette below. Kept as text on purpose -- diffs are
 *  readable, there are no binary assets, and a fix to the art is a one-letter edit. */

/** A squat red fire crocodile: cream face and belly, two flame tufts, outlined and shaded (41x49 cells). */
export const FIRE_CROC: PixelArt = {
  palette: {
    K: '#141010',
    O: '#7E1F10',
    R: '#F44A30',
    D: '#E03812',
    X: '#F85A12',
    P: '#EC6A5A',
    C: '#FAF6DC',
    W: '#FFFFFF',
    Y: '#F8D000',
    A: '#F8A000',
    B: '#B86800',
    G: '#333848',
    S: '#B0A090',
    N: '#805840',
  },
  frames: [
    // idle
    [
      '............................XX...........',
      '...........................XYYX..........',
      '..........................XYYYX..........',
      '..........................XYYYYX.........',
      '....................XX...XYYYYYX.........',
      '...................XYX...XYYYYYYX........',
      '..................XYYYX.XYYYYYYYX........',
      '..................XYYYX.XYYYYYXX.........',
      '...................XYYYXXYYYXX...........',
      '....................XYYYXYYX.............',
      '....................OOOYYYX..OOO.........',
      '..................OOPCCOOYXOOCCCO........',
      '.................ORPCCCCCORRCCCCCN.......',
      '................ORRCCCCCCCCCCCCCCCN......',
      '...............ORRPCCCCCCCCCCCCCCCN......',
      '..............ORRRCCCCCSGSCCCCSGSCCN.....',
      '..............ORRRCCCCCGWGCCCCGWGCCN.....',
      '.............ORRRPCCCCCGSGCCCCGNNNNNN....',
      '.............ORRRCCCCCCGGGCCNNNCCCCCCNN..',
      '............KDRRRCCCCCCSGNNNCCCCCCCCCCCN.',
      '............KRRRRCCCCCCNNCCCCCCKKCCCKKCCN',
      '............KRRRRCCCCCSCCCCCCCCSKCCCKSCCN',
      '...........KDRRRRPCCCCCCCCCCCCCCCCCCCCCCN',
      '...........KRRRRRRCCCCCCCCCCCCCCCCCCCCCK.',
      '...........KRRRRRRPCCCCCCCCSKKKKSSKKSCK..',
      '...........KRRRRRRRPCCCCSKKKGGKWWWWGKK...',
      '...........KRRRRRRRROKKKKPPPGGGKWWKK.....',
      '...........KRRRRRRRROPPPPPPPPPGGKK.......',
      '...........ORRRRRRRRROPPPPPPPPPGGK.......',
      '..........KRRRRRRRRRROPPPKPPPPPPGKK......',
      '..........KRRRRRRRRRRROPKWKPPPPPKWKO.....',
      '..........ORRRRRRRRRRRRKSWKPPPPPKWODO....',
      '.........KDRRRRRRRRRRDRRKKOPPPPGKORDO....',
      '.........KDDRRRRRRRRRRDKKRROKKKKDRRORO...',
      '........KDDDRRRRRRRRORRRRKKRRRRRRDORRO...',
      '......OOBDDDRRRRRODRORRRRRRODDDOOORRRK...',
      '...OOOAABDDORRRRRRODDORRRRODDDDDDORORK...',
      '.OODBAABDDDORRRRRRRODDOROKKDBBBBDDKOK....',
      'KDDDDDDDDDDODRRRRRRODDDKODDBAAAABDOK.....',
      'KSSDDDDDDSKDDRRRRRRDOSSDDDDAAAAABKK......',
      '.KGSSSSSSSKDDDDRRRDDOSSSSSBAAAABKDK......',
      '...KKGSSSSKDDDDDDDDDOSSSSSBBBBKKDOGK.....',
      '......KKKKKDDDDKDDDKOSSSSSSSKKOGKOGK.....',
      '..........KDDDKGKDGGKSSSSGKKDDOGKOGGK....',
      '..........KDDDKGGKGGGKKKK.KDDKGGGKGGK....',
      '..........KDDKGGGKGGGK.....KKKGGGKKK.....',
      '...........KKKGGGGKGGK........KKK........',
      '.............KKGGGKKK....................',
      '...............KKK.......................',
    ],
    // blink
    [
      '............................XX...........',
      '...........................XYYX..........',
      '..........................XYYYX..........',
      '..........................XYYYYX.........',
      '....................XX...XYYYYYX.........',
      '...................XYX...XYYYYYYX........',
      '..................XYYYX.XYYYYYYYX........',
      '..................XYYYX.XYYYYYXX.........',
      '...................XYYYXXYYYXX...........',
      '....................XYYYXYYX.............',
      '....................OOOYYYX..OOO.........',
      '..................OOPCCOOYXOOCCCO........',
      '.................ORPCCCCCORRCCCCCN.......',
      '................ORRCCCCCCCCCCCCCCCN......',
      '...............ORRPCCCCCCCCCCCCCCCN......',
      '..............ORRRCCCCCCCCCCCCCCCCCN.....',
      '..............ORRRCCCCCCCCCCCCCCCCCN.....',
      '.............ORRRPCCCCCNNNCCCCNNNNNNN....',
      '.............ORRRCCCCCCGGGCCNNNCCCCCCNN..',
      '............KDRRRCCCCCCSGNNNCCCCCCCCCCCN.',
      '............KRRRRCCCCCCNNCCCCCCKKCCCKKCCN',
      '............KRRRRCCCCCSCCCCCCCCSKCCCKSCCN',
      '...........KDRRRRPCCCCCCCCCCCCCCCCCCCCCCN',
      '...........KRRRRRRCCCCCCCCCCCCCCCCCCCCCK.',
      '...........KRRRRRRPCCCCCCCCSKKKKSSKKSCK..',
      '...........KRRRRRRRPCCCCSKKKGGKWWWWGKK...',
      '...........KRRRRRRRROKKKKPPPGGGKWWKK.....',
      '...........KRRRRRRRROPPPPPPPPPGGKK.......',
      '...........ORRRRRRRRROPPPPPPPPPGGK.......',
      '..........KRRRRRRRRRROPPPKPPPPPPGKK......',
      '..........KRRRRRRRRRRROPKWKPPPPPKWKO.....',
      '..........ORRRRRRRRRRRRKSWKPPPPPKWODO....',
      '.........KDRRRRRRRRRRDRRKKOPPPPGKORDO....',
      '.........KDDRRRRRRRRRRDKKRROKKKKDRRORO...',
      '........KDDDRRRRRRRRORRRRKKRRRRRRDORRO...',
      '......OOBDDDRRRRRODRORRRRRRODDDOOORRRK...',
      '...OOOAABDDORRRRRRODDORRRRODDDDDDORORK...',
      '.OODBAABDDDORRRRRRRODDOROKKDBBBBDDKOK....',
      'KDDDDDDDDDDODRRRRRRODDDKODDBAAAABDOK.....',
      'KSSDDDDDDSKDDRRRRRRDOSSDDDDAAAAABKK......',
      '.KGSSSSSSSKDDDDRRRDDOSSSSSBAAAABKDK......',
      '...KKGSSSSKDDDDDDDDDOSSSSSBBBBKKDOGK.....',
      '......KKKKKDDDDKDDDKOSSSSSSSKKOGKOGK.....',
      '..........KDDDKGKDGGKSSSSGKKDDOGKOGGK....',
      '..........KDDDKGGKGGGKKKK.KDDKGGGKGGK....',
      '..........KDDKGGGKGGGK.....KKKGGGKKK.....',
      '...........KKKGGGGKGGK........KKK........',
      '.............KKGGGKKK....................',
      '...............KKK.......................',
    ],
    // jump
    [
      '............................XX...........',
      '...........................XYYX..........',
      '..........................XYYYX..........',
      '..........................XYYYYX.........',
      '....................XX...XYYYYYX.........',
      '...................XYX...XYYYYYYX.XX.....',
      '..................XYYYX.XYYYYYYYXXYYX....',
      '..................XYYYX.XYYYYYXX.XYYX....',
      '...................XYYYXXYYYXX..XYYYX....',
      '....................XYYYXYYX....XYYX.....',
      '....................OOOYYYX..OOO.........',
      '..................OOPCCOOYXOOCCCO........',
      '.................ORPCCCCCORRCCCCCN.......',
      '................ORRCCCCCCCCCCCCCCCN......',
      '...............ORRPCCCCCCCCCCCCCCCN......',
      '..............ORRRCCCCCSGSCCCCSGSCCN.....',
      '..............ORRRCCCCCGWGCCCCGWGCCN.....',
      '.............ORRRPCCCCCGSGCCCCGNNNNNN....',
      '.............ORRRCCCCCCGGGCCNNNCCCCCCNN..',
      '............KDRRRCCCCCCSGNNNCCCCCCCCCCCN.',
      '............KRRRRCCCCCCNNCCCCCCKKCCCKKCCN',
      '............KRRRRCCCCCSCCCCCCCCSKCCCKSCCN',
      '...........KDRRRRPCCCCCCCCCCCCCCCCCCCCCCN',
      '...........KRRRRRRCCCCCCCCCCCCCCCCCCCCCK.',
      '...........KRRRRRRPCCCCCCCCSKKKKSSKKSCK..',
      '...........KRRRRRRRPCCCCSKKKGGKWWWWGKK...',
      '...........KRRRRRRRROKKKKPPPGGGKWWKK.....',
      '...........KRRRRRRRROPPPPPPPPPGGKK.......',
      '...........ORRRRRRRRROPPPPPPPPPGGK.......',
      '..........KRRRRRRRRRROPPPKPPPPPPGKK......',
      '..........KRRRRRRRRRRROPKWKPPPPPKWKO.....',
      '..........ORRRRRRRRRRRRKSWKPPPPPKWODO....',
      '.........KDRRRRRRRRRRDRRKKOPPPPGKORDO....',
      '.........KDDRRRRRRRRRRDKKRROKKKKDRRORO...',
      '........KDDDRRRRRRRRORRRRKKRRRRRRDORRO...',
      '......OOBDDDRRRRRODRORRRRRRODDDOOORRRK...',
      '...OOOAABDDORRRRRRODDORRRRODDDDDDORORK...',
      '.OODBAABDDDORRRRRRRODDOROKKDBBBBDDKOK....',
      'KDDDDDDDDDDODRRRRRRODDDKODDBAAAABDOK.....',
      'KSSDDDDDDSKDDRRRRRRDOSSDDDDAAAAABKK......',
      '.KGSSSSSSSKDDDDRRRDDOSSSSSBAAAABKDK......',
      '...KKGSSSSKDDDDDDDDDOSSSSSBBBBKKDOGK.....',
      '......KKKKKDDDDKDDDKOSSSSSSSKKOGKOGK.....',
      '..........KDDDKGKDGGKSSSSGKKDDOGKOGGK....',
      '..........KDDDKGGKGGGKKKK.KDDKGGGKGGK....',
      '..........KDDKGGGKGGGK.....KKKGGGKKK.....',
      '...........KKKGGGGKGGK........KKK........',
      '.............KKGGGKKK....................',
      '...............KKK.......................',
    ],
  ],
};

/** A chibi white giant robot with a blue chest, red abdomen and feet, and a yellow V-crest, outlined and shaded (28x48 cells). */
export const MECHA: PixelArt = {
  palette: {
    K: '#22262E',
    W: '#F4F4F2',
    S: '#C9CDD6',
    B: '#2C52B3',
    U: '#1F3C86',
    R: '#E0302F',
    D: '#A82222',
    Y: '#F8D23C',
    H: '#3A3F47',
    G: '#7A8290',
    O: '#FF8C1A',
    L: '#FFE066',
  },
  frames: [
    // idle
    [
      '.....KK................KK...',
      '.....KYK..............KYK...',
      '......KYYK..........KYYK....',
      '.......KYYYYKRRKYYYYK.......',
      '.......KWWWWKRRKWWWWK.......',
      '......KWWWWWWKKWWWWWWSK.....',
      '.....KWWWWWWWWWWWWWWWSSK....',
      '....KYKWWWWWWWWWWWWWSKYK....',
      '....KYKHHHHHHHHHHHHHHKYK....',
      '....KWKHHYYHHHHHHYYHHKWK....',
      '.....KKHHHHHHHHHHHHHHKK.....',
      '......KWWWWWKWWKWWWWWSK.....',
      '......KWWWWWKWWKWWWWWSK.....',
      '.......KWWWWWWWWWWWWSK......',
      '........KWWWKRRKWWWSK.......',
      '.........KKKKKRRKKKKK.......',
      '...........KGGGGGK..........',
      '..........KKGGGGGKK.........',
      '.KKKKKKKSYYKBBBBKYYSKKKKKKK.',
      'KWWWWWWKSYYKBBBBKYYSKWWWWWWK',
      'KWWWWWWKSYYKBBBBKYYSKWWWWWSK',
      'KWWWWWWKBBBBBBBBBBBBKWWWWWSK',
      'KWWWWWWKBBBBUBBUBBBBKWWWWWSK',
      'KWWWWWSKBBBBUBBUBBBBKWWWWSSK',
      'KKKKKKKKBBBBBBBBBBBBKKKKKKKK',
      '.KWWSK.KRRRRRRRRRRRRK.KWWSK.',
      '.KWWSK.KRRRRDRRDRRRRK.KWWSK.',
      '.KGGGK.KWWWWWWWWWWWWK.KGGGK.',
      '.KWWSK.KWWWWKYYKWWWWK.KWWSK.',
      '.KWWSK.KWWWKYYYYKWWWK.KWWSK.',
      '.KWWSK..KWWWSKKWWWSK..KWWSK.',
      '.KWWSK..KWWWSKKWWWSK..KWWSK.',
      '.KHHHK..KWWWSKKWWWSK..KHHHK.',
      '.KHHHK..KWWWSKKWWWSK..KHHHK.',
      '..KKK...KGGGGKKGGGGK...KKK..',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '.......KRRRRDKKRRRRDK.......',
      '.......KRRRRDKKRRRRDK.......',
      '.......KRRRRDKKRRRRDK.......',
      '.......KGGGGGKKGGGGGK.......',
      '.......KKKKKKKKKKKKKK.......',
      '............................',
      '............................',
      '............................',
      '............................',
    ],
    // lit
    [
      '.....KK................KK...',
      '.....KYK..............KYK...',
      '......KYYK..........KYYK....',
      '.......KYYYYKRRKYYYYK.......',
      '.......KWWWWKRRKWWWWK.......',
      '......KWWWWWWKKWWWWWWSK.....',
      '.....KWWWWWWWWWWWWWWWSSK....',
      '....KYKWWWWWWWWWWWWWSKYK....',
      '....KYKHHHHHHHHHHHHHHKYK....',
      '....KWKHHYYHHHHHHYYHHKWK....',
      '.....KKHHHHHHHHHHHHHHKK.....',
      '......KWWWWWKWWKWWWWWSK.....',
      '......KWWWWWKWWKWWWWWSK.....',
      '.......KWWWWWWWWWWWWSK......',
      '........KWWWKRRKWWWSK.......',
      '.........KKKKKRRKKKKK.......',
      '...........KGGGGGK..........',
      '..........KKGGGGGKK.........',
      '.KKKKKKKSYYKBBBBKYYSKKKKKKK.',
      'KWWWWWWKSYYKBBBBKYYSKWWWWWWK',
      'KWWWWWWKSYYKBBBBKYYSKWWWWWSK',
      'KWWWWWWKBBBBBBBBBBBBKWWWWWSK',
      'KWWWWWWKBBBBUBBUBBBBKWWWWWSK',
      'KWWWWWSKBBBBUBBUBBBBKWWWWSSK',
      'KKKKKKKKBBBBBBBBBBBBKKKKKKKK',
      '.KWWSK.KRRRRRRRRRRRRK.KWWSK.',
      '.KWWSK.KRRRRDRRDRRRRK.KWWSK.',
      '.KGGGK.KWWWWWWWWWWWWK.KGGGK.',
      '.KWWSK.KWWWWKYYKWWWWK.KWWSK.',
      '.KWWSK.KWWWKYYYYKWWWK.KWWSK.',
      '.KWWSK..KWWWSKKWWWSK..KWWSK.',
      '.KWWSK..KWWWSKKWWWSK..KWWSK.',
      '.KHHHK..KWWWSKKWWWSK..KHHHK.',
      '.KHHHK..KWWWSKKWWWSK..KHHHK.',
      '..KKK...KGGGGKKGGGGK...KKK..',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '.......KRRRRDKKRRRRDK.......',
      '.......KRRRRDKKRRRRDK.......',
      '.......KRRRRDKKRRRRDK.......',
      '.......KGGGGGKKGGGGGK.......',
      '.......KKKKKKKKKKKKKK.......',
      '........OOOOO..OOOOO........',
      '.........OLLO....OLLO.......',
      '..........OO......OO........',
      '............................',
    ],
    // flight
    [
      '.....KK................KK...',
      '.....KYK..............KYK...',
      '......KYYK..........KYYK....',
      '.......KYYYYKRRKYYYYK.......',
      '.......KWWWWKRRKWWWWK.......',
      '......KWWWWWWKKWWWWWWSK.....',
      '.....KWWWWWWWWWWWWWWWSSK....',
      '....KYKWWWWWWWWWWWWWSKYK....',
      '....KYKHHHHHHHHHHHHHHKYK....',
      '....KWKHHYYHHHHHHYYHHKWK....',
      '.....KKHHHHHHHHHHHHHHKK.....',
      '......KWWWWWKWWKWWWWWSK.....',
      '......KWWWWWKWWKWWWWWSK.....',
      '.......KWWWWWWWWWWWWSK......',
      '........KWWWKRRKWWWSK.......',
      '.........KKKKKRRKKKKK.......',
      '...........KGGGGGK..........',
      '..........KKGGGGGKK.........',
      '.KKKKKKKSYYKBBBBKYYSKKKKKKK.',
      'KWWWWWWKSYYKBBBBKYYSKWWWWWWK',
      'KWWWWWWKSYYKBBBBKYYSKWWWWWSK',
      'KWWWWWWKBBBBBBBBBBBBKWWWWWSK',
      'KWWWWWWKBBBBUBBUBBBBKWWWWWSK',
      'KWWWWWSKBBBBUBBUBBBBKWWWWSSK',
      'KKKKKKKKBBBBBBBBBBBBKKKKKKKK',
      '.KWWSK.KRRRRRRRRRRRRK.KWWSK.',
      '.KWWSK.KRRRRDRRDRRRRK.KWWSK.',
      '.KGGGK.KWWWWWWWWWWWWK.KGGGK.',
      '.KWWSK.KWWWWKYYKWWWWK.KWWSK.',
      '.KWWSK.KWWWKYYYYKWWWK.KWWSK.',
      '.KWWSK..KWWWSKKWWWSK..KWWSK.',
      '.KWWSK..KWWWSKKWWWSK..KWWSK.',
      '.KHHHK..KWWWSKKWWWSK..KHHHK.',
      '.KHHHK..KWWWSKKWWWSK..KHHHK.',
      '..KKK...KGGGGKKGGGGK...KKK..',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '........KWWWSKKWWWSK........',
      '.......KRRRRDKKRRRRDK.......',
      '.......KRRRRDKKRRRRDK.......',
      '.......KRRRRDKKRRRRDK.......',
      '.......KGGGGGKKGGGGGK.......',
      '.......KKKKKKKKKKKKKK.......',
      '.......OOOOOOO.OOOOOOO......',
      '........OLLLLO..OLLLLO......',
      '.........OLLO....OLLO.......',
      '..........OO......OO........',
    ],
  ],
};

/** Frame indices, so the scene code reads as poses rather than numbers. */
export const CROC_FRAME = { idle: 0, blink: 1, jump: 2 } as const;
export const MECHA_FRAME = { idle: 0, lit: 1, flight: 2 } as const;
