import { PixelArt } from '../../shared/pixel-sprite/pixel-sprite';

/** The Team page's two pixel-art surprises (see AboutTeam). Each is a few frames of a character
 *  grid: one letter per cell, `.` transparent, palette below. Drawn by hand at this size on
 *  purpose -- text diffs, no binary assets, and a reviewer can read the picture. */

/** A squat red fire crocodile with a cream face and belly, square yellow scales and two flame tufts (28x26 cells). */
export const FIRE_CROC: PixelArt = {
  palette: {
    R: '#E64A3B',
    D: '#B5342A',
    C: '#FBF3DD',
    Y: '#F7D23E',
    L: '#FFF0A0',
    K: '#1E1A1A',
    M: '#6B2A22',
    P: '#E8776F',
    W: '#FFFFFF',
  },
  frames: [
    // idle
    [
      '............Y...............',
      '...........YL...Y...........',
      '...........YLY.LY...........',
      '...........YYY.YY...........',
      '..........RRRCCCCCCCCC......',
      '........RRRRRCCCCCCCCCCC....',
      '.......RRRRRRCCKKCCCKKCCCC..',
      '......RRRRRRRCCKKCCCKKCCCCC.',
      '.....RRRRRRRRCCKKCCCKKCCCCKC',
      '.....RRRRRRRRRCCCCCCCCCCCCCC',
      '.....RRRRRRRRRMMCCCCCCCCCCCC',
      '.....RRRRRRRRRRCMMMMMMMMMMMM',
      '......RRRRRRRRRCPPWPPPWPPWC.',
      '.......RRRRRRRRRCCCCCCCCC...',
      '........RRRRRRRRRCCCCCC.....',
      '.......RRRRRRRRRRRRRDDDDDD..',
      '.....RRRRRRRRRRRRRRRDRRRCD..',
      '....RRRRRRRRRRRRRRRRDDDDDD..',
      '...RRRRRRRRRRRCCCCCCCCCRRR..',
      'RRDRRRRRRRRRRRCCCCYYCCCCRR..',
      'RYYDRRRRRRRRRRCCCCYYCCCCRR..',
      'RYYDRRRRRRRRRRRCCCCCCCCRR...',
      'CCCDDRRRRRRRRRRRCCCCCCRR....',
      '.......RRRRRR...RRRRRRR.....',
      '......RRRRRRK...RRRRRRRK....',
      '......RRRRKRK...RRRRRKRK....',
    ],
    // blink
    [
      '............Y...............',
      '...........YL...Y...........',
      '...........YLY.LY...........',
      '...........YYY.YY...........',
      '..........RRRCCCCCCCCC......',
      '........RRRRRCCCCCCCCCCC....',
      '.......RRRRRRCCCCCCCCCCCCC..',
      '......RRRRRRRCCCCCCCCCCCCCC.',
      '.....RRRRRRRRCCKKCCCKKCCCCKC',
      '.....RRRRRRRRRCCCCCCCCCCCCCC',
      '.....RRRRRRRRRMMCCCCCCCCCCCC',
      '.....RRRRRRRRRRCMMMMMMMMMMMM',
      '......RRRRRRRRRCPPWPPPWPPWC.',
      '.......RRRRRRRRRCCCCCCCCC...',
      '........RRRRRRRRRCCCCCC.....',
      '.......RRRRRRRRRRRRRDDDDDD..',
      '.....RRRRRRRRRRRRRRRDRRRCD..',
      '....RRRRRRRRRRRRRRRRDDDDDD..',
      '...RRRRRRRRRRRCCCCCCCCCRRR..',
      'RRDRRRRRRRRRRRCCCCYYCCCCRR..',
      'RYYDRRRRRRRRRRCCCCYYCCCCRR..',
      'RYYDRRRRRRRRRRRCCCCCCCCRR...',
      'CCCDDRRRRRRRRRRRCCCCCCRR....',
      '.......RRRRRR...RRRRRRR.....',
      '......RRRRRRK...RRRRRRRK....',
      '......RRRRKRK...RRRRRKRK....',
    ],
    // jump
    [
      '............Y......Y........',
      '...........YL...Y..Y........',
      '...........YLY.LY.YL........',
      '...........YYY.YY.YY........',
      '..........RRRCCCCCCCCC......',
      '........RRRRRCCCCCCCCCCC....',
      '.......RRRRRRCCKKCCCKKCCCC..',
      '......RRRRRRRCCKKCCCKKCCCCC.',
      '.....RRRRRRRRCCKKCCCKKCCCCKC',
      '.....RRRRRRRRRCCCCCCCCCCCCCC',
      '.....RRRRRRRRRMMCCCCCCCCCCCC',
      '.....RRRRRRRRRRCMMMMMMMMMMMM',
      '......RRRRRRRRRCPPPPPPPPPWC.',
      '.......RRRRRRRRRCPWPPPWPC.RD',
      '........RRRRRRRRRCCCCCC.RRD.',
      '.......RRRRRRRRRRRRRRRRRRDD.',
      '.....RRRRRRRRRRRRRRRRRRRD...',
      '....RRRRRRRRRRRRRRRRDDDD....',
      '...RRRRRRRRRRRCCCCCCCCCRRR..',
      'RRDRRRRRRRRRRRCCCCYYCCCCRR..',
      'RYYDRRRRRRRRRRCCCCYYCCCCRR..',
      'RYYDRRRRRRRRRRRCCCCCCCCRR...',
      'CCCDDRRRRRRRRRRRCCCCCCRR....',
      '......RRRRRRR...RRRRRRRR....',
      '......RRRRRKK...RRRRRRKK....',
      '......YYYYYYY...YYYYYYYY....',
    ],
  ],
};

/** A chibi white giant robot with a blue chest, red abdomen and feet, and a yellow V-crest (20x34 cells). */
export const MECHA: PixelArt = {
  palette: {
    W: '#F4F4F2',
    S: '#CBCFD6',
    B: '#2C52B3',
    R: '#E0302F',
    Y: '#F8D23C',
    K: '#3A3F47',
    G: '#6E7480',
    O: '#FF8C1A',
    L: '#FFE066',
  },
  frames: [
    // idle
    [
      '...Y............Y...',
      '....YY........YY....',
      '......YY.RR.YY......',
      '.....WWWYYYYWWW.....',
      '....WWWWWWWWWWWW....',
      '...YWWKKKKKKKKWWY...',
      '...YWWKYYKKYYKWWY...',
      '....WWKKKKKKKKWW....',
      '....WWWWGWWGWWWW....',
      '..S.WWWWGWWGWWWW.S..',
      '..S..WWWWRRWWWW..S..',
      '..S...GGGGGGGG...S..',
      'WWWWSYYBBBBBBYYSWWWW',
      'WWWWSYYBBBBBBYYSWWWW',
      'WWWWSBBBBBBBBBBSWWWW',
      'WWWWSBBBBBBBBBBSWWWW',
      'SWWS.RRRRRRRRRR.SWWS',
      '.WW..RRRRRRRRRR..WW.',
      '.GG..WWWWWWWWWW..GG.',
      '.WW..WWWYYYYWWW..WW.',
      '.WW..WWWWYYWWWW..WW.',
      '.KK..WWWW..WWWW..KK.',
      '.KK..WWWW..WWWW..KK.',
      '.....GGGG..GGGG.....',
      '.....WWWW..WWWW.....',
      '.....WWWW..WWWW.....',
      '....RRRRR..RRRRR....',
      '....RRRRR..RRRRR....',
      '....GGGGG..GGGGG....',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
    // lit
    [
      '...Y............Y...',
      '....YY........YY....',
      '......YY.RR.YY......',
      '.....WWWYYYYWWW.....',
      '....WWWWWWWWWWWW....',
      '...YWWKKKKKKKKWWY...',
      '...YWWKYYKKYYKWWY...',
      '....WWKKKKKKKKWW....',
      '....WWWWGWWGWWWW....',
      '..S.WWWWGWWGWWWW.S..',
      '..S..WWWWRRWWWW..S..',
      '..S...GGGGGGGG...S..',
      'WWWWSYYBBBBBBYYSWWWW',
      'WWWWSYYBBBBBBYYSWWWW',
      'WWWWSBBBBBBBBBBSWWWW',
      'WWWWSBBBBBBBBBBSWWWW',
      'SWWS.RRRRRRRRRR.SWWS',
      '.WW..RRRRRRRRRR..WW.',
      '.GG..WWWWWWWWWW..GG.',
      '.WW..WWWYYYYWWW..WW.',
      '.WW..WWWWYYWWWW..WW.',
      '.KK..WWWW..WWWW..KK.',
      '.KK..WWWW..WWWW..KK.',
      '.....GGGG..GGGG.....',
      '.....WWWW..WWWW.....',
      '.....WWWW..WWWW.....',
      '....RRRRR..RRRRR....',
      '....RRRRR..RRRRR....',
      '....GGGGG..GGGGG....',
      '.....OOOO..OOOO.....',
      '.....OLLO..OLLO.....',
      '......OO....OO......',
      '....................',
      '....................',
    ],
    // flight
    [
      '...Y............Y...',
      '....YY........YY....',
      '......YY.RR.YY......',
      '.....WWWYYYYWWW.....',
      '....WWWWWWWWWWWW....',
      '...YWWKKKKKKKKWWY...',
      '...YWWKYYKKYYKWWY...',
      '....WWKKKKKKKKWW....',
      '....WWWWGWWGWWWW....',
      '..S.WWWWGWWGWWWW.S..',
      '..S..WWWWRRWWWW..S..',
      '..S...GGGGGGGG...S..',
      'WWWWSYYBBBBBBYYSWWWW',
      'WWWWSYYBBBBBBYYSWWWW',
      'WWWWSBBBBBBBBBBSWWWW',
      'WWWWSBBBBBBBBBBSWWWW',
      'SWWS.RRRRRRRRRR.SWWS',
      'WW...RRRRRRRRRR...WW',
      'GG...WWWWWWWWWW...GG',
      'WW...WWWYYYYWWW...WW',
      'WW...WWWWYYWWWW...WW',
      'KK...WWWW..WWWW...KK',
      'KK...WWWW..WWWW...KK',
      '.....GGGG..GGGG.....',
      '.....WWWW..WWWW.....',
      '.....WWWW..WWWW.....',
      '....RRRRR..RRRRR....',
      '....RRRRR..RRRRR....',
      '....GGGGG..GGGGG....',
      '....OOOOO..OOOOO....',
      '....OLLLO..OLLLO....',
      '.....OLO....OLO.....',
      '......O......O......',
      '......O......O......',
    ],
  ],
};

/** Frame indices, so the scene code reads as poses rather than numbers. */
export const CROC_FRAME = { idle: 0, blink: 1, jump: 2 } as const;
export const MECHA_FRAME = { idle: 0, lit: 1, flight: 2 } as const;
