/**
 * Mirrors schema/stats/facet-stats.json, generated by schema/generate_facet_stats.py.
 *
 * These counts are precomputed once per data update rather than aggregated per query: the corpus
 * is refreshed 6-12 times a year in triage batches, so live aggregation over 827k documents would
 * be the most expensive thing on the search page for data that barely moves.
 */

export interface FacetCount {
  value: string;
  /** Absent where no real corpus figure is available yet -- render the option without a count
   *  rather than showing a fixture-scale number as if it were corpus truth. */
  count?: number;
}

export interface YearRange {
  min: number;
  max: number;
}

/** The real, full-corpus headline figures -- these are corpus-wide even while `facets` below are
 *  still fixture-derived. See `corpus_provenance` in the generated file. */
export interface CorpusStats {
  total: number;
  positive: number;
  negative: number;
  undeterminable: number;
  openAccess: number;
  fulltextAvailable: number;
  enriched: number;
}

export interface FacetStats {
  generated: string;
  schema_version: string;
  /** 'fixture' while the search page runs on the 200-record dev sample; 'full-corpus' from
   *  Phase 5 onward. The search page shows its development-preview banner when this is 'fixture'. */
  source: 'fixture' | 'full-corpus';
  records_counted: number;
  corpus: CorpusStats;
  corpus_provenance: string;
  facets: {
    classification: FacetCount[];
    license: FacetCount[];
    pubTypes: FacetCount[];
    domainTier1: FacetCount[];
    learningParadigm: FacetCount[];
    modelFamily: FacetCount[];
    yearRange: YearRange | null;
  };
}
